---
- name: deploy vagrant vm playbook
  hosts: win
  tasks:
    - name: initiate vagrant centos7 vm
      win_shell: "cd C:\HashiCorp\Centos8 ; vagrant up --provider hyperv"
      
          
          
          
    - name: install httpd
      yum: name=httpd
    - name: enable and start httpd
      service: name=httpd enabled=true state=started
    - name: create index.html
      copy: 
        content: "welcome dude!"
        dest: /var/www/html/index.html
        mode: 0444
    - name: open firewall port
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

...
