---
- hosts: home
  gather_facts: yes
  tasks:
      - name: Make BG directory on each client
        command: mkdir -p /home/onesaf/Desktop/Pictures/BG   
        become: no
      - name: rsync the NOFORN BANNER to each client
        command: rsync -azvh mhopper@debian9:/home/onesaf/Desktop/BG/ /home/onesaf/Desktop/Pictures/BG/
      - name: Set the NOFORN BANNER on each client
        command: gsettings set org.gnome.desktop.background picture-uri file:///home/onesaf/Desktop/Pictures/BG/NOFORN_BANNER.jpg
 
        become: no
